language: php

node_js:
  - "node"
  - "8"

sudo: false

cache:
  yarn: true
  directories:
    - "$HOME/.composer/cache"

matrix:
  include:
    # PHP 7.1 tests
    - language: php
      php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
      before_script:
        - composer update $COMPOSER_FLAGS --prefer-dist
      script: vendor/bin/phpunit
    - language: php
      php: 7.1
      env: COMPOSER_FLAGS="--prefer-stable"
      before_script:
        - composer update $COMPOSER_FLAGS --prefer-dist
      script: vendor/bin/phpunit
    - language: php
      php: 7.1
      env: COMPOSER_FLAGS=""
      before_script:
        - composer update $COMPOSER_FLAGS --prefer-dist
      script: vendor/bin/phpunit
    - language: php
      php: 7.1
      env: SYMFONY_VERSION="4.0.*"
      before_script:
        - composer update $COMPOSER_FLAGS --prefer-dist
      script: vendor/bin/phpunit

    # PHP 7.2 tests
    - language: php
      php: 7.2
      env: COMPOSER_FLAGS=""
      before_script:
        - composer update $COMPOSER_FLAGS --prefer-dist
      script: vendor/bin/phpunit
    - language: php
      php: 7.2
      env: SYMFONY_VERSION="4.0.*"
      before_script:
        - composer update $COMPOSER_FLAGS --prefer-dist
      script: vendor/bin/phpunit

    # JS tests
    - language: node_js
      node_js: 8.5.0
      env: YARN_TEST="TRUE"
      before_script:
        - yarn install
      script: yarn test
