language: php

node_js:
  - "node"
  - "8"

sudo: false

cache:
  directories:
    - "$HOME/.composer/cache"

matrix:
  include:
    # PHP tests
    - language: php
      php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
      before_script:
        - composer update $COMPOSER_FLAGS --prefer-dist
      script: vendor/bin/phpunit
    - language: php
      php: 7.1
      env: COMPOSER_FLAGS="--prefer-stable"
      before_script:
        - composer update $COMPOSER_FLAGS --prefer-dist
      script: vendor/bin/phpunit
    - language: php
      php: 7.1
      env: COMPOSER_FLAGS=""
      before_script:
        - composer update $COMPOSER_FLAGS --prefer-dist
      script: vendor/bin/phpunit

    # JS tests
    - language: node_js
      node_js: 8.5.0
      before_script:
        - npm install
      script: node_modules/.bin/jasmine
