build: false
platform: 'x86'
clone_folder: C:\projects\asset-lib

cache:
  - node_modules
  - '%LOCALAPPDATA%/Yarn'
  - '%LOCALAPPDATA%\Composer\files'

branches:
  except:
    - gh-pages

## Install PHP and composer, and run the appropriate composer command
install:
  - ps: Set-Service wuauserv -StartupType Manual
  - cinst -y --params '""/InstallDir:C:\tools\php""' php 
  - refreshenv
  - cd c:\tools\php
  - copy php.ini-production php.ini /Y
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - cd %APPVEYOR_BUILD_FOLDER%
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar install --prefer-dist --no-interaction
  - yarn install

## Run the actual test
test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - vendor\bin\phpunit.bat
  - yarn test
